### ISSUE TITLE
requirements.txt has unpinned flask and mailersend, breaking fresh installs

### ISSUE THREAD

**Issue by AndresBallares** [BlitzKraft/saythanks.io#516]
## Summary

Following a fresh setup (native venv + local Postgres, per `docs/saythanks_development.md` / `docs/saythanks.io_setup.md`), `pip install -r requirements.txt` installs the latest versions of two packages that are incompatible with the current code, and the app fails to boot.

## Bugs

**1. `flask` is unpinned → installs Flask 3.1.3, which removed `flask.Markup`**

`saythanks/core.py` does:
```python
from flask import abort, redirect, Markup, make_response
```
Flask dropped this re-export in 2.3 (it now lives in `markupsafe.Markup`). Result:
```
ImportError: cannot import name 'Markup' from 'flask'
```
Fix: pin `flask<2.3` in `requirements.txt` (tested working with `Flask==2.2.5`), or update the import to `from markupsafe import Markup`.

**2. `mailersend` is unpinned → installs mailersend 2.0.0, a full API rewrite**

`saythanks/myemail.py` does:
```python
from mailersend import emails
...
mailer = emails.NewEmail(mailersend_api_key)
```
This `emails.NewEmail` interface only exists in mailersend <1.0. The current PyPI release (2.0.0) is a ground-up SDK rewrite with a different module layout (`client.py`, `builders/`, `resources/`). Result:
```
ImportError: cannot import name 'emails' from 'mailersend'
```
Fix: pin `mailersend==0.6.0` in `requirements.txt` (last pre-rewrite release, confirmed working with the existing `myemail.py` code), or migrate `myemail.py` to the new SDK.

## Bonus: doc/config drift

`conf_template/site.env` and `sample.env` still reference `SENDGRID_API_KEY`, but `saythanks/myemail.py` reads `MAILERSEND_API_KEY` (matching the MailerSend migration mentioned in the README). Neither template currently lists `MAILERSEND_API_KEY`, so following the docs literally won't produce a working `.env`.

## Repro

```
python3 -m venv .venv
.venv/bin/pip install -r requirements.txt
# set up local Postgres + DATABASE_URL, load saythanks/sqls/schema.sql
.venv/bin/python t.py
# ImportError: cannot import name 'Markup' from 'flask'
```

## Suggested fix

- Pin `flask<2.3` and `mailersend==0.6.0` in `requirements.txt`
- Add `MAILERSEND_API_KEY` (and drop `SENDGRID_API_KEY`) from `conf_template/site.env` and `sample.env`

Happy to open a PR with these pins if useful.

**Comment by kgashok** [comment]
> ## Suggested fix
> * Pin `flask<2.3` and `mailersend==0.6.0` in `requirements.txt`
> * Add `MAILERSEND_API_KEY` (and drop `SENDGRID_API_KEY`) from `conf_template/site.env` and `sample.env`
> 
> Happy to open a PR with these pins if useful.

@AndresBallares Historically, we have struggled to get a working app if we start using the latest versions of various packages. Please see [this](https://github.com/BlitzKraft/saythanks.io/blob/master/docs/saythanks_development.md) as to how you can go about setting a working local development setup. For example, I think we use an older version of Python to compile the whole app. @dinesh131 is our deployment expert for saythanks and is aware of this more than I am. 

But if you are confident if your pins will not break the setup of local dev environment, let's go for it. I would prefer to move forward than stay stuck in the past, FWIW.

**Comment by nandhakumar-murugan** [comment]
Hi @kgashok sir and @AndresBallares,

I have opened PR #538 to stabilize fresh installs while preserving a rock-solid local development environment:
- **Dependency Pins:** Pinned \lask<2.3\ and \mailersend==0.6.0\ in \
equirements.txt\ to prevent breaking API changes in recent package releases.
- **Import Migration:** Updated \saythanks/core.py\ to import \Markup\ directly from \markupsafe\ instead of \lask\.
- **Environment Consistency:** Aligned \sample.env\, \conf_template/site.env\, and \DEVELOPMENT.md\ to use \MAILERSEND_API_KEY\ and \AUTH0_JWT_V2_TOKEN\.

All modules pass bytecode compilation (\compileall\). Ready for review!
