### PR TITLE
fix: pin flask and mailersend in requirements.txt, update env templates (#516)

### LINKED ISSUE #516: requirements.txt has unpinned flask and mailersend, breaking fresh installs
## Summary

Following a fresh setup (native venv + local Postgres, per `docs/saythanks_development.md` / `docs/saythanks.io_setup.md`), `pip install -r requirements.txt` installs the latest versions of two packages that are incompatible with the current code, and the app fails to boot.

## Bugs

**1. `flask` is unpinned → installs Flask 3.1.3, which removed `flask.Markup`**

`saythanks/core.py` does:
```python
from flask import abort, redirect, Markup, make_response
```
Flask dropped this re-export in 2.3 (it now lives in `markupsafe.Markup`). Result:
```
ImportError: cannot import name 'Markup' from 'flask'
```
Fix: pin `flask<2.3` in `requirements.txt` (tested working with `Flask==2.2.5`), or update the import to `from markupsafe import Markup`.

**2. `mailersend` is unpinned → installs mailersend 2.0.0, a full API rewrite**

`saythanks/myemail.py` does:
```python
from mailersend import emails
...
mailer = emails.NewEmail(mailersend_api_key)
```
This `emails.NewEmail` interface only exists in mailersend <1.0. The current PyPI release (2.0.0) is a ground-up SDK rewrite with a different module layout (`client.py`, `builders/`, `resources/`). Result:
```
ImportError: cannot import name 'emails' from 'mailersend'
```
Fix: pin `mailersend==0.6.0` in `requirements.txt` (last pre-rewrite release, confirmed working with the existing `myemail.py` code), or migrate `myemail.py` to the new SDK.

## Bonus: doc/config drift

`conf_template/site.env` and `sample.env` still reference `SENDGRID_API_KEY`, but `saythanks/myemail.py` reads `MAILERSEND_API_KEY` (matching the MailerSend migration mentioned in the README). Neither template currently lists `MAILERSEND_API_KEY`, so following the docs literally won't produce a working `.env`.

## Repro

```
python3 -m venv .venv
.venv/bin/pip install -r requirements.txt
# set up local Postgres + DATABASE_URL, load saythanks/sqls/schema.sql
.venv/bin/python t.py
# ImportError: cannot import name 'Markup' from 'flask'
```

## Suggested fix

- Pin `flask<2.3` and `mailersend==0.6.0` in `requirements.txt`
- Add `MAILERSEND_API_KEY` (and drop `SENDGRID_API_KEY`) from `conf_template/site.env` and `sample.env`

Happy to open a PR with these pins if useful.

### PR DESCRIPTION
**Pull request by nandhakumar-murugan**
Resolves #516

### Summary
Following a fresh installation, \pip install -r requirements.txt\ installed unpinned versions of \lask\ (Flask 3.x) and \mailersend\ (MailerSend 2.x), which resulted in runtime \ImportError\ exceptions on boot:
1. \ImportError: cannot import name 'Markup' from 'flask'\ (due to removal in Flask 2.3+).
2. \ImportError: cannot import name 'emails' from 'mailersend'\ (due to SDK architectural rewrite in MailerSend 2.0.0).

Additionally, legacy references to \SENDGRID_API_KEY\ remained in template configuration files, causing drift from the MailerSend provider implementation.

### Key Changes
- **\
equirements.txt\**:
  - Pinned \lask<2.3\ to guarantee stability with existing Flask extensions.
  - Pinned \mailersend==0.6.0\ to restore compatibility with \saythanks/myemail.py\ (\emails.NewEmail\ interface).
- **\saythanks/core.py\**:
  - Updated \Markup\ import to import from \markupsafe\ directly, ensuring forward compatibility across Flask versions.
- **Environment Templates**:
  - Updated \conf_template/site.env\, \sample.env\, and \DEVELOPMENT.md\ to reference \MAILERSEND_API_KEY\ instead of \SENDGRID_API_KEY\.
  - Added missing \AUTH0_CLIENT_SECRET\ to \sample.env\.

### Verification
- Verified all Python modules compile cleanly (\python -m py_compile\).
- Confirmed \site.env\ and \sample.env\ accurately reflect the environment variables read by the application.

### CODE REVIEW

**Comment by nandhakumar-murugan** [comment]
Addressed the Copilot review feedback in commit \155e49\: updated \DEVELOPMENT.md\ to specify \AUTH0_JWT_V2_TOKEN\ matching the application code (\saythanks/core.py\) and the environment templates (\sample.env\ and \conf_template/site.env\).
